### ISSUE TITLE
有两个问题请教一下

### ISSUE THREAD

**Issue by elrondliu** [alibaba-flutter/flutter-boot#1]
1. android_shell目录是做什么的?
2. 如何debug dart代码?

**Comment by sayhixiang** [comment]
@elrondliu 

1. android/ios_shell目前主要用来不依赖业务代码的产物打包
2. debug dart代码还是按官方步骤走，从flutter工程run起来，打断点，attach

**Comment by elrondliu** [comment]
@sayhixiang 感谢解答.
我们这边遇到了两个问题:
1. 在Native工程做一些改动, 在Module工程运行App发现改动没有生效, 偶现.
2. Flutter无法attach, 也是偶现
