### ISSUE TITLE
到flutter-boot init就走不下去了

### ISSUE THREAD

**Issue by KAICW** [alibaba-flutter/flutter-boot#10]
flutter-boot init
info [init] init flutter module.
? 请输入flutter工程名称： my_flutter_module
然后就一直在这里卡住
环境是：
[√] Flutter (Channel stable, v1.9.1+hotfix.5, on Microsoft Windows [Version 10.0.17134.1069], locale zh-CN)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.5)
[√] Connected device (1 available)

**Comment by voicewitness** [comment]
尝试下flutter1.5.4呢

**Comment by KAICW** [comment]
还是一样效果

**Comment by voicewitness** [comment]
控制台的日志贴一下看看

**Comment by po1arbear** [comment]
一样

**Comment by Jenus** [comment]
window版本下, 确实有这类问题, 从代码上看,  停在了init命令中
const flutterRepo = (await ui.input('请输入flutter仓库地址，回车跳过')).trim()
这一行,

经过观察, boot依赖的inquirer库比较老,  另外对于版本里的type为input的prompt官方github上有人提出挂起现象,  官方提出是Remove events listeners导致的bug.

先将c:\%userprofile%\AppData\Roaming\npm\node_modules\flutter-boot\node-modules\inquirer\lib\ui\baseUI.js文件中, close函数体全部注释掉, 代码可以继续执行.
下面是close函数体:
```
UI.prototype.close = function () {
  // Remove events listeners
  this.rl.removeListener('SIGINT', this.onForceClose);
  process.removeListener('exit', this.onForceClose);

  // Restore prompt functionnalities
  this.rl.output.unmute();

  // Close the readline
  this.rl.output.end();
  this.rl.pause();
  this.rl.close();
};
```

**Comment by Jenus** [comment]
@voicewitness 
关于inquirer的版本是否可以调整一下, 目前是
/usr/local/lib
└─┬ flutter-boot@0.0.5
  ├─┬ eslint@5.16.0
  │ └── inquirer@6.5.2 

线上最新版本好像是6.12.0.

目前mac系统没有问题,  window系统有这个挂起的问题.

**Comment by Jenus** [comment]
@KAICW @po1arbear 
为了在window下面进行下去, 可以这样临时改动一下:
先把本地安装的flutter-boot卸载掉,然后修改源文件依赖库inquirer为最新的版本号(起码在当前程序调用到的api接口是兼容的).

具体设计到的命令如下:
npm uninstall flutter-boot -g        //卸载命令

找到flutter-boot-master工程目录下的package.json(为了方便比较是否安装成功, 可以修改一下本地的版本号, 比如说0.0.6)
   "version": "0.0.5",      =》      "version": "0.0.6",      //这个没有必要 
  "inquirer": "^1.1.2",      =》      "inquirer": "^6.5.2",

改好后, 在flutter-boot-master/目录下执行install命令
npm install  -g                //注意这个是源码目录, 所以不要在指定module名称了


正常修改成功后, 可以用 npm list flutter-boot - g, 看到版本是0.0.6(如果上面已经修改过的话)就ok了

**Comment by Jenus** [comment]
@voicewitness @KAICW 
windows系统做symlink的话, 还需要管理权限(!!!需要用管理者权限打开cmd)
所以, 如果是没有管理权限, 需要做
“Copy xxx folder when symlink fails”

基于以上, 建议还是用mac系统作为开发机器^-^

**Comment by voicewitness** [comment]
参考@Jenus 的推荐方式，升级了inquirer库

**Comment by kingrukawa** [comment]
mac 也卡了
