### ISSUE TITLE
Flutter boost compatible problem

### ISSUE THREAD

**Issue by Jenus** [alibaba-flutter/flutter-boot#11]
Currently, version 1.9 of flutter is supported when using Flutter boost.Why does flutter_boost version fixed at 0.1.52(latest stable version is 0.1.54)? 

Some problems found:
(1)  onPostResume api in BoostFlutterEngine is removed;
(2) DartExecutor.DartEntrypoint api has changed;
(3) getBoostPluginRegistry is renamed with getPluginRegistry

**Comment by Jenus** [comment]
BTW: 
Supporting dependency syntax like the following:
               url: 'https://github.com/alibaba/flutter_boost.git'
                ref: 'feature/flutter_1.9_upgrade'

**Comment by voicewitness** [comment]
We're supporting the latest version of flutter including making the version of flutter_boost optional.

**Comment by Raynor999** [comment]
> We're supporting the latest version of flutter including making the version of flutter_boost optional.

if could, hope to support it as soon as possible.  
1.5.4-hotfix version of flutter is not support for macOS Catalina , Please🙏

**Comment by voicewitness** [comment]
^0.0.6 supports
