### ISSUE TITLE
Unresolved reference: FBInitializer

### ISSUE THREAD

**Issue by etzuk** [alibaba-flutter/flutter-boot#12]
I did 1,2 steps without errors but in step 3 while I tried adding FBInitializer.init(this) to my Application class unresolved reference error occurs. 

Try to search for FBInitializer class without any success so I wondering if the guide is updated?

**Comment by Jenus** [comment]
Just like:
package com.example.my_android

import android.app.Application
import com.example.fbi.fb.FBInitializer

class MyApplication: Application() {
    override fun onCreate() {
        super.onCreate()

        FBInitializer.init(this)
    }
}

Of course you will import the class of  FBInitializer firstly. If error not disappeared,  you can comment this snipper of FBInitializer.init(this), then compile it again.  Any effect?

**Comment by Jenus** [comment]
BTW:  
In FBInitializer, there is one deprecated api calling(DartExecutor.DartEntrypoint) when using latest 1.9.1hot-fixed flutter. So modify it as the following to exclude compiling error:
@Override
            public IFlutterEngineProvider engineProvider() {
                return new BoostEngineProvider() {
                    @Override
                    public BoostFlutterEngine createEngine(Context context) {
                        return new BoostFlutterEngine(context,
                                new DartExecutor.DartEntrypoint(
//                                        context.getResources().getAssets(),
                                        FlutterMain.findAppBundlePath(), "main"),
                                "/");
                    }
                };
            }
