### ISSUE TITLE
How can I upgrade flutter-boost version? 

### ISSUE THREAD

**Issue by thirtyyuan** [alibaba-flutter/flutter-boot#16]
I'm try to upgrade `flutter-boost` version by modify `flutter_boost` version to `0.1.54` which in `pubspec.yaml`, but after I use `flutter-boot user` in my native project, it'll be rollback to `0.1.52`. How can I upgrade flutter-boost version? 
BTW, maybe you should update `README`, it's out of style about `flutter boost`, that let me feel I was unsuccessfully to exec `flutter-boot use`.

**Comment by thirtyyuan** [comment]
Another question is have any idea about `.gitignore` when using `flutter-boot`? Which should I add to `.gitignore` when using `flutter-boot`?

**Comment by Jenus** [comment]
@thirtyyuan 
As the author's feedback about selection btw different boost versions in https://github.com/alibaba-flutter/flutter-boot/issues/11,  it will be supported in one future version or next release.

**Comment by voicewitness** [comment]
^0.0.6 supports
