### ISSUE TITLE
关联iOS项目出错

### ISSUE THREAD

**Issue by wenlei1990** [alibaba-flutter/flutter-boot#18]
<img width="614" alt="屏幕快照 2019-11-07 下午5 56 10" src="https://user-images.githubusercontent.com/5211438/68379096-35527d80-0188-11ea-8c83-d45fac1b79f3.png">

sudo gem install -n /usr/local/bin xcodeproj
单独执行了这个命令，还是不行

**Comment by wenlei1990** [comment]
<img width="567" alt="屏幕快照 2019-11-07 下午6 29 36" src="https://user-images.githubusercontent.com/5211438/68381408-a2681200-018c-11ea-86c1-bc807c0922a6.png">

**Comment by yinma848** [comment]
这个问题看起来是因为gem没有安装成功，因为/usr/bin路径没有写权限。这个问题其实是苹果的策略，从Mac "El Capitan"开始，/System, /bin, /sbin, or /usr (except /usr/local)这几个路径就默认不能更改了。细节可以看看：
https://apple.stackexchange.com/questions/193368/what-is-the-rootless-feature-in-el-capitan-really?newreg=068dc403fea74a3eb1e434b955924023
以及
https://superuser.com/questions/717663/permission-denied-when-trying-to-cd-usr-local-bin-from-terminal
