### ISSUE TITLE
ios 工程报错

### ISSUE THREAD

**Issue by brave723** [alibaba-flutter/flutter-boot#3]
* /Users/xx/Library/Developer/Xcode/DerivedData/Runner-cmxrntjkhweendhhhuvnampmpzbd/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Script-C025048EEDBE123D022C86B6.sh: line 2: /packages/flutter_tools/bin/xcode_backend.sh: No such file or directory
* /Users/xx/Library/Developer/Xcode/DerivedData/Runner-cmxrntjkhweendhhhuvnampmpzbd/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Script-C025048EEDBE123D022C86B6.sh: line 3: /packages/flutter_tools/bin/xcode_backend.sh: No such file or directory

flutter1.9.1版本，创建完工程报这个错，请问怎么处理？

**Comment by voicewitness** [comment]
操作流程是怎么样的

**Comment by voicewitness** [comment]
有更多线索时再打开

**Comment by Jenus** [comment]
@voicewitness 

目前在我机器上重现的步骤是:
就是创建一个新的iOS工程, 然后执行命令行 flutter-boot init;
随后按照提示选择对应iOS的project名称, 然后生成Runner target(这个还是需要注释掉依赖条件, 见prepare Runner target 脚本出错 #6, 最后的说明), 
随后打开iOS的workspace, 选择Runner target进行编译就出现了问题

**Comment by Jenus** [comment]
根据源码分析,  正常有一个Generated.xcconfig文件, 然后将对应的相关配置信息继承下来, 但根据ios项目里Podfile里配置信息跟踪:
=》eval(File.read(File.join(File.dirname(__FILE__), 'fbpodhelper.rb')), binding)
=》eval(File.read(File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')), binding)
=》podhelper.rb文件里(没有入口函数)的各个函数没有被调用到, 怎么起作用?!!!

毕竟, Flutter-boost中的example里, 有类似这样的主动调用:
 # Flutter Pods
  generated_xcode_build_settings = parse_KV_file('./Flutter/Generated.xcconfig')
  if generated_xcode_build_settings.empty?
    puts "Generated.xcconfig must exist. If you're running pod install manually, make sure flutter packages get is executed first."
  end
  generated_xcode_build_settings.map { |p|
    if p[:name] == 'FLUTTER_FRAMEWORK_DIR'
      symlink = File.join('.symlinks', 'flutter')
      File.symlink(File.dirname(p[:path]), symlink)
      pod 'Flutter', :path => File.join(symlink, File.basename(p[:path]))
    end
  }
  # Plugin Pods
  plugin_pods = parse_KV_file('../.flutter-plugins')
  plugin_pods.map { |p|
    symlink = File.join('.symlinks', 'plugins', p[:name])
    File.symlink(p[:path], symlink)
    pod p[:name], :path => File.join(p[:path], 'ios')
  }

**Comment by yinma848** [comment]
> 根据源码分析, 正常有一个Generated.xcconfig文件, 然后将对应的相关配置信息继承下来, 但根据ios项目里Podfile里配置信息跟踪:
> =》eval(File.read(File.join(File.dirname(**FILE**), 'fbpodhelper.rb')), binding)
> =》eval(File.read(File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')), binding)
> =》podhelper.rb文件里(没有入口函数)的各个函数没有被调用到, 怎么起作用?!!!
> 
> 毕竟, Flutter-boost中的example里, 有类似这样的主动调用:
> 
> # Flutter Pods
> generated_xcode_build_settings = parse_KV_file('./Flutter/Generated.xcconfig')
> if generated_xcode_build_settings.empty?
> puts "Generated.xcconfig must exist. If you're running pod install manually, make sure flutter packages get is executed first."
> end
> generated_xcode_build_settings.map { |p|
> if p[:name] == 'FLUTTER_FRAMEWORK_DIR'
> symlink = File.join('.symlinks', 'flutter')
> File.symlink(File.dirname(p[:path]), symlink)
> pod 'Flutter', :path => File.join(symlink, File.basename(p[:path]))
> end
> }
> 
> # Plugin Pods
> plugin_pods = parse_KV_file('../.flutter-plugins')
> plugin_pods.map { |p|
> symlink = File.join('.symlinks', 'plugins', p[:name])
> File.symlink(p[:path], symlink)
> pod p[:name], :path => File.join(p[:path], 'ios')
> }

你这里提到的是flutter1.9的情况，相比1.5，flutter1.9的podhelper.rb在实现上有比较大的变化，因此造成podfile的实现需要有相应的修改。目前对1.9的适配正在进行中。
