### ISSUE TITLE
AndroidX支持问题，建议在init时可供选择

### ISSUE THREAD

**Issue by henryxie2093** [alibaba-flutter/flutter-boot#5]

**Comment by sayhixiang** [comment]
是的，下个版本我们加上，感谢

**Comment by Jenus** [comment]
@sayhixiang 
临时处理方式, 根据Boost里feature/flutter_1.9_androidx_upgrade分支改动(参考这个分支的修改记录), 
需要修改的主要地方是:
Flutter_Boost模块下面的:
gradle.properties文件里增加:
android.enableJetifier=true
android.useAndroidX=true

对应的gradle.builde文件里对应的android.support.x修改为:
   implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation 'androidx.appcompat:appcompat:1.0.0'
    implementation 'androidx.annotation:annotation:1.0.0'
    implementation 'android.arch.lifecycle:common-java8:1.1.1'

随后, 相关对应的文件其实可以采用转换为androidX的refactor命令来操作, 只是可能转换不完全, 需要手动改动一些代码断的import.
