### ISSUE TITLE
prepare Runner target 脚本出错

### ISSUE THREAD

**Issue by zxwo0o** [alibaba-flutter/flutter-boot#6]
info [link] Running flutter boot link...
sill [link] checking current path...
sill [link] checking platform...
sill [link] linking...
info [link] xcode already settled
sill [link] prepare Runner target
/Users/zxwo0o/Work/TouchiOS/MallModule/Example
Traceback (most recent call last):
/usr/local/lib/node_modules/flutter-boot/src/ios/duplicate_target.rb:105:in `<main>': undefined method `uuid' for nil:NilClass (NoMethodError)
ERR! [link] error when add Runner target to project.Error: Command failed: ruby /usr/local/lib/node_modules/flutter-boot/src/ios/duplicate_target.rb /Users/zxwo0o/Work/TouchiOS/MallModule/Example/MallModule.xcodeproj MallModule Runner
sill [link] prepare Runner target to podfile
sill [link] no target found in Podfile, start:target 'MallModule' do;runnerStart:target 'Runner' do
info [link] inject gitignore

**Comment by yinma848** [comment]
请问你的ios工程中有与工程同名的target吗？（也即有名为MallModule的target吗？）
目前duplicate_target.rb的逻辑是取与工程同名的target来做复制操作的。

另外，可以提供进一步的信息吗？比如XCode的版本，Flutter的版本等。我们目前的版本只支持到flutter1.5，对1.9的适配还在进行中。

**Comment by yinma848** [comment]
> info [link] Running flutter boot link...
> sill [link] checking current path...
> sill [link] checking platform...
> sill [link] linking...
> info [link] xcode already settled
> sill [link] prepare Runner target
> /Users/zxwo0o/Work/TouchiOS/MallModule/Example
> Traceback (most recent call last):
> /usr/local/lib/node_modules/flutter-boot/src/ios/duplicate_target.rb:105:in `<main>': undefined method `uuid' for nil:NilClass (NoMethodError)
> ERR! [link] error when add Runner target to project.Error: Command failed: ruby /usr/local/lib/node_modules/flutter-boot/src/ios/duplicate_target.rb /Users/zxwo0o/Work/TouchiOS/MallModule/Example/MallModule.xcodeproj MallModule Runner
> sill [link] prepare Runner target to podfile
> sill [link] no target found in Podfile, start:target 'MallModule' do;runnerStart:target 'Runner' do
> info [link] inject gitignore

请问你的ios工程中有与工程同名的target吗？（也即有名为MallModule的target吗？）
目前duplicate_target.rb的逻辑是取与工程同名的target来做复制操作的。

另外，可以提供进一步的信息吗？比如XCode的版本，Flutter的版本等。我们目前的版本只支持到flutter1.5，对1.9的适配还在进行中。

**Comment by zxwo0o** [comment]
工程名称是没错的，flutter用的不是1.5版本，git里拉取的master分支，（可能是这个原因，等会尝试下）Xcode Version 11.0 (11A420a)

**Comment by zxwo0o** [comment]
尝试降级到1.5.4 还是有问题 ： 目前只执行到在podfile中写入 tag Runner pod的配置。
? iOS工程本地地址，回车跳过 /Users/zxwo0o/Work/TouchiOS
sill [link] checking platform...
sill [link] linking...
sill [link] updating xcode setting
/Users/zxwo0o/Work/TouchiOS
Successfully installed xcodeproj-1.13.0
Parsing documentation for xcodeproj-1.13.0
Done installing documentation for xcodeproj after 0 seconds
1 gem installed
sill [link] prepare Runner target
/Users/zxwo0o/Work/TouchiOS
sill [link] prepare Runner target to podfile
info [link] inject gitignore
/Users/zxwo0o/Work/TouchiOS
Analyzing dependencies
[!] Unable to find a target named `Runner`, did find `Touch`, `TouchTest`, and `TouchBuild`.
(node:54612) UnhandledPromiseRejectionWarning: Error: Command failed: pod install
    at checkExecSyncError (child_process.js:621:11)
    at execSync (child_process.js:657:15)
    at linker.execSync (/usr/local/lib/node_modules/flutter-boot/src/ios/link.js:40:5)
    at linker.link (/usr/local/lib/node_modules/flutter-boot/src/ios/link.js:63:10)
    at BaseLinker.link (/usr/local/lib/node_modules/flutter-boot/src/generator/linker.js:30:12)
    at init (/usr/local/lib/node_modules/flutter-boot/src/commands/init.js:72:16)
    at async Command.<anonymous> (/usr/local/lib/node_modules/flutter-boot/src/commands/init.js:26:7)
(node:54612) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:54612) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.   
工程名和 tag名称都是一致的  
环境 ：
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, v1.5.4-hotfix.2, on Mac OS X 10.14.5 18F132, locale zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] iOS toolchain - develop for iOS devices (Xcode 11.0)
[✓] Android Studio (version 3.5)
[✓] Connected device (1 available)

• No issues found!

**Comment by yinma848** [comment]
> 尝试降级到1.5.4 还是有问题 ： 目前只执行到在podfile中写入 tag Runner pod的配置。
> ? iOS工程本地地址，回车跳过 /Users/zxwo0o/Work/TouchiOS
> sill [link] checking platform...
> sill [link] linking...
> sill [link] updating xcode setting
> /Users/zxwo0o/Work/TouchiOS
> Successfully installed xcodeproj-1.13.0
> Parsing documentation for xcodeproj-1.13.0
> Done installing documentation for xcodeproj after 0 seconds
> 1 gem installed
> sill [link] prepare Runner target
> /Users/zxwo0o/Work/TouchiOS
> sill [link] prepare Runner target to podfile
> info [link] inject gitignore
> /Users/zxwo0o/Work/TouchiOS
> Analyzing dependencies
> [!] Unable to find a target named `Runner`, did find `Touch`, `TouchTest`, and `TouchBuild`.
> (node:54612) UnhandledPromiseRejectionWarning: Error: Command failed: pod install
> at checkExecSyncError (child_process.js:621:11)
> at execSync (child_process.js:657:15)
> at linker.execSync (/usr/local/lib/node_modules/flutter-boot/src/ios/link.js:40:5)
> at linker.link (/usr/local/lib/node_modules/flutter-boot/src/ios/link.js:63:10)
> at BaseLinker.link (/usr/local/lib/node_modules/flutter-boot/src/generator/linker.js:30:12)
> at init (/usr/local/lib/node_modules/flutter-boot/src/commands/init.js:72:16)
> at async Command. (/usr/local/lib/node_modules/flutter-boot/src/commands/init.js:26:7)
> (node:54612) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> (node:54612) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> 工程名和 tag名称都是一致的
> 环境 ：
> Doctor summary (to see all details, run flutter doctor -v):
> [✓] Flutter (Channel unknown, v1.5.4-hotfix.2, on Mac OS X 10.14.5 18F132, locale zh-Hans-CN)
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
> [✓] iOS toolchain - develop for iOS devices (Xcode 11.0)
> [✓] Android Studio (version 3.5)
> [✓] Connected device (1 available)
> 
> • No issues found!

方便提供这个工程的podfile吗？我尝试本地复现一下这种情况。

**Comment by zxwo0o** [comment]
# Created by flutter-boot
target 'Runner' do
  
    pod  'HBPublic', :git => 'http://xxxxx/HBPublic.git' , :branch => 'develop'      (私有库地址)
    pod  'SDWebImage' ,'5.0.6'
    pod  'libwebp', '1.0.2'
    pod  'Masonry'
    pod  'CocoaLumberjack', '3.5.2'
    pod  'YYText'
    pod  'Bugly' , '2.5.0'
    pod  'GrowingAutoTrackKit', '2.8.3'
    pod  'GTSDK' , '2.3.0.0'
    pod  'UMengAnalytics', '4.2.4'
    pod  'Socket.IO-Client-Swift', '14.0.0'
    pod  'RMStore', '0.7.1'
    pod  'PLPlayerKit', '3.4.3'
    pod  'PLMediaStreamingKit', '2.3.3'
    pod  'SVProgressHUD', '2.2.5'
    pod  'SSZipArchive' , '2.2.2'
    pod  'AgoraRtcEngine_iOS', '2.4.0.1'
    pod  'lottie-ios', '2.5.3'
    pod  'GInsightSDK'
    

  eval(File.read(File.join(File.dirname(__FILE__), 'fbpodhelper.rb')), binding)

end


有换个了其他工程集成也还是一样的报错

**Comment by yinma848** [comment]
> # Created by flutter-boot
> target 'Runner' do
> 
> ```
> pod  'HBPublic', :git => 'http://xxxxx/HBPublic.git' , :branch => 'develop'      (私有库地址)
> pod  'SDWebImage' ,'5.0.6'
> pod  'libwebp', '1.0.2'
> pod  'Masonry'
> pod  'CocoaLumberjack', '3.5.2'
> pod  'YYText'
> pod  'Bugly' , '2.5.0'
> pod  'GrowingAutoTrackKit', '2.8.3'
> pod  'GTSDK' , '2.3.0.0'
> pod  'UMengAnalytics', '4.2.4'
> pod  'Socket.IO-Client-Swift', '14.0.0'
> pod  'RMStore', '0.7.1'
> pod  'PLPlayerKit', '3.4.3'
> pod  'PLMediaStreamingKit', '2.3.3'
> pod  'SVProgressHUD', '2.2.5'
> pod  'SSZipArchive' , '2.2.2'
> pod  'AgoraRtcEngine_iOS', '2.4.0.1'
> pod  'lottie-ios', '2.5.3'
> pod  'GInsightSDK'
> ```
> 
> eval(File.read(File.join(File.dirname(**FILE**), 'fbpodhelper.rb')), binding)
> 
> end
> 
> 有换个了其他工程集成也还是一样的报错

这里报错的log来看（[!] Unable to find a target named Runner, did find Touch, TouchTest, and TouchBuild.），主要问题是在工程中没有正确生成名为Runner的target。而从你给我的podfile看，podfile这边是正确生成的Runner target。所以看起来问题是和工程本身有关。
不过我在本地确实没有找到复现的路径，可以方便提供给我一个demo工程吗？

**Comment by yinma848** [comment]
待有进一步回复后可重新打开

**Comment by Jenus** [comment]
@yinma848 
if !dependencies_array.empty?
        create_runner_target(proj, src_target, dependencies_array)
    end


请问这个条件为何要加上? 对于一般的(新建的)干净的没有自己的podfile的项目, 这个目前测试下来就是没有依赖项.  导致后续的Runner target无法复制出来.

**Comment by yinma848** [comment]
> @yinma848
> if !dependencies_array.empty?
> create_runner_target(proj, src_target, dependencies_array)
> end
> 
> 请问这个条件为何要加上? 对于一般的(新建的)干净的没有自己的podfile的项目, 这个目前测试下来就是没有依赖项. 导致后续的Runner target无法复制出来.

如你所说，这个条件确实不是必须的，不应该过分限制。
