### ISSUE TITLE
iOS init 后，工程并没有接入flutter.framework

### ISSUE THREAD

**Issue by ZSWForC** [alibaba-flutter/flutter-boot#7]
iOS原生项目 init 后，工程并没有接入flutter.framework，也没有flutter_boost.framework。所以选择用create、link、use命令重新生成一次，过程中项目有FBDemoRouter文件生成，但还是没有关于flutter的库生成。而且在执行use命令时需要打开防火墙，自动pod update的时候更新第三方库到最新版本，修改pod库源地址；最后也没有flutter_boost.framework生成。观察发现原生iOS项目的profile并没有eval(File.read(File.join(File.dirname(__FILE__), 'fbpodhelper.rb')), binding)命令，反而是flutter中的runner项目的profile有eval(File.read(File.join(File.dirname(__FILE__), 'fbpodhelper.rb')), binding)。

**Comment by voicewitness** [comment]
使用步骤参考如下：https://github.com/alibaba-flutter/flutter-boot#%E5%AE%89%E8%A3%85
首先init；
然后使用use来选择你需要的boost版本（截止回复前只有一个可选版本）；
最后打开ios工程，选择target runner，然后尝试运行；

**Comment by voicewitness** [comment]
> 而且在执行use命令时需要打开防火墙，

需要提供下打开防火墙的上下文日志

**Comment by Jenus** [comment]
@voicewitness 
你本地在一个干净的环境下, 能完成项目的构建吗?

我这边操作流程如下:
(1) 在一个目录下如TestFlutter, 新建一个my_ios的oc工程(TestFlutter/my_ios), 没有任何pod依赖, 所以也没有用pod init执行(这个配置是否会出现一个bug: 就是生成Runner target时, 有一个依赖项不会空的限制, 所以导致Runner target拷贝工程失败---我hack掉这个判断);
(2) 然后在这个TestFlutter目录下执行flutter-boot init命令, 这个过程很长, 但有一个地方我观察到,
      a) 会将生成flutter module目录下的iOS目录重命名为ios_shell, 然后用ios目录soft link这个ios_shell;
            因为看到这个ios_shell目录下面, 有Podfile, 这个podfile里会调用
            install_flutter_engine_pod
            install_flutter_plugin_pods flutter_application_path
     这个根据boost上的理解, 应该是构建原生对flutter的依赖(???)
      b) 当时, 后续选择对应的ios工程为my_ios之后, 又会触发新的soft link, 将flutter module目录下面的ios目录soft link对应的原生工程my_ios, 从这个角度来讲, 倒是构建**flutter视角**的意思.
     疑问是: ios_shell的连接性就丧失掉了, 如何构建**原生视角**???
(3) 等init构成结束, 是否可以按照原生视角打开原生的workspace, 然后对Runner target进行编译?
     疑问是: 此时相关的环境没有构建起来, 其中的flutter_export_environment.sh, 貌似没有任何地方触发到? 所以项目中的ScriptPhrase:  FLUTTER_ROOT找不到, 导致编译不了

以上, 静等答复, 😄  jenus.newie@gmail.com, 保持沟通

**Comment by Jenus** [comment]
@voicewitness 
当然, 能有一个demo构建好的example, 或者示例图快照(最好是workspace里的项目关系图)也可以参考一下, 多谢.

**Comment by Jenus** [comment]
@yinma848 
确实如你所说, flutter 1.9以后对1.5版本对podhelper.rb文件做了很大对修改以及对应对podfile.tmpl也修改了.  链接是:https://github.com/flutter/flutter/blob/v1.5.0/packages/flutter_tools/templates/module/ios/library/Flutter.tmpl/podhelper.rb. 所以期待你们下个兼容版本[目前来讲, flutter版本降级来开发或者实验的开发者体验不太好^-^], 非常感谢你们的努力和付出.

**Comment by yinma848** [comment]
> @yinma848
> 确实如你所说, flutter 1.9以后对1.5版本对podhelper.rb文件做了很大对修改以及对应对podfile.tmpl也修改了. 链接是:https://github.com/flutter/flutter/blob/v1.5.0/packages/flutter_tools/templates/module/ios/library/Flutter.tmpl/podhelper.rb. 所以期待你们下个兼容版本[目前来讲, flutter版本降级来开发或者实验的开发者体验不太好^-^], 非常感谢你们的努力和付出.

确实如此，其实从iOS测来看，flutter1.9最主要的变化就是修改了podhelper.rb，而这就直接影响了podfile的写法。另外1.9版本的podhelper.rb还增加了对build phases的配置，其实这一步之前是flutter-boot实现的，因此也需要相应调整。

**Comment by shuaishuai0814** [comment]
这个问题要如何解决呢？flutter最新版本是没法接入吗？

**Comment by Jenus** [comment]
@shuaishuai0814 
你如果要用最新的版本,  估计目前只能根据官方的手动方案了(https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps), 然后等flutter-boot兼容版本发布后支持@yinma848
