### ISSUE TITLE
Command PhaseScriptExecution failed with a nonzero exit code

### ISSUE THREAD

**Issue by webaifei** [alibaba-flutter/flutter-boot#9]
IOS 工程提示报错

/Users/u51/Library/Developer/Xcode/DerivedData/book-bmdewmjvgignncfeidhkhwtzumft/Build/Intermediates.noindex/book.build/Debug-iphonesimulator/book.build/Script-666766485AA9A92097AB28CD.sh: line 2: /packages/flutter_tools/bin/xcode_backend.sh: No such file or directory
/Users/u51/Library/Developer/Xcode/DerivedData/book-bmdewmjvgignncfeidhkhwtzumft/Build/Intermediates.noindex/book.build/Debug-iphonesimulator/book.build/Script-666766485AA9A92097AB28CD.sh: line 3: /packages/flutter_tools/bin/xcode_backend.sh: No such file or directory
Command PhaseScriptExecution failed with a nonzero exit code

**Comment by yinma848** [comment]
这个看起来是$FLUTTER_ROOT环境变量没有成功导入，正确的路径是$FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh
可以检查一下Generated.xcconfig文件是否存在，或者定义是否正确。如果没有可以运行flutter build ios生成Generated.xcconfig

**Comment by yinma848** [comment]
> IOS 工程提示报错
> 
> /Users/u51/Library/Developer/Xcode/DerivedData/book-bmdewmjvgignncfeidhkhwtzumft/Build/Intermediates.noindex/book.build/Debug-iphonesimulator/book.build/Script-666766485AA9A92097AB28CD.sh: line 2: /packages/flutter_tools/bin/xcode_backend.sh: No such file or directory
> /Users/u51/Library/Developer/Xcode/DerivedData/book-bmdewmjvgignncfeidhkhwtzumft/Build/Intermediates.noindex/book.build/Debug-iphonesimulator/book.build/Script-666766485AA9A92097AB28CD.sh: line 3: /packages/flutter_tools/bin/xcode_backend.sh: No such file or directory
> Command PhaseScriptExecution failed with a nonzero exit code

这个看起来是$FLUTTER_ROOT环境变量没有成功导入，正确的路径是$FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh
可以检查一下Generated.xcconfig文件是否存在，或者定义是否正确。如果没有可以运行flutter build ios生成Generated.xcconfig

**Comment by yinma848** [comment]
待有进一步回复后可以重新打开

**Comment by Jenus** [comment]
@yinma848 
疑问是为何会缺少Generated.xcconfig?  正常init 命令后, 这个目录下面, 就会有.ios/Flutter/Generated.xcconfig.  
正常flutter-boot的命令包装了flutter的命令, 所以正常在从原生视角来看的话, 不需要再单独执行flutter的命令, 这样理解对吗?

**Comment by yinma848** [comment]
> @yinma848
> 疑问是为何会缺少Generated.xcconfig? 正常init 命令后, 这个目录下面, 就会有.ios/Flutter/Generated.xcconfig.
> 正常flutter-boot的命令包装了flutter的命令, 所以正常在从原生视角来看的话, 不需要再单独执行flutter的命令, 这样理解对吗?
是的，你目前是用的flutter1.9吗？因为我们这个发布的时候只支持到1.5

**Comment by Jenus** [comment]
对的  是flutter1.9 hotfix版本
